import 'package:json_annotation/json_annotation.dart';

part 'group.g.dart'; // This part file will be generated by json_serializable

/// Class for storing group data.
@JsonSerializable()
class Group {
  Group({required this.id, required this.name});

  factory Group.fromJson(Map<String, dynamic> json) => _$GroupFromJson(json);

  Map<String, dynamic> toJson() => _$GroupToJson(this);

  @JsonKey(name: 'id')
  final String id;
  @JsonKey(name: 'name')
  final String name;
}
