import 'package:json_annotation/json_annotation.dart';

part 'subject.g.dart'; // This part file will be generated by json_serializable

/// Class for storing subject data.
@JsonSerializable()
class Subject {
  Subject({required this.id, required this.brief, required this.title});

  factory Subject.fromJson(Map<String, dynamic> json) =>
      _$SubjectFromJson(json);

  Map<String, dynamic> toJson() => _$SubjectToJson(this);

  @JsonKey(name: 'id')
  final String id;
  final String brief;
  final String title;
}
