import 'package:json_annotation/json_annotation.dart';
import 'package:nure_timetable/models/entity.dart';

part 'teacher.g.dart'; // This part file will be generated by json_serializable

/// Class for storing teacher data.
@JsonSerializable()
class Teacher {
  Teacher({
    required this.id,
    required this.shortName,
    required this.fullName,
    required this.department,
    required this.faculty,
  });

  factory Teacher.fromJson(Map<String, dynamic> json) =>
      _$TeacherFromJson(json);

  Map<String, dynamic> toJson() => _$TeacherToJson(this);

  @JsonKey(name: 'id')
  final int id;
  @JsonKey(name: 'shortName')
  final String shortName;
  @JsonKey(name: 'fullName')
  final String fullName;
  @JsonKey(name: 'department')
  final Entity department;
  @JsonKey(name: 'faculty')
  final Entity faculty;
}
