import 'package:json_annotation/json_annotation.dart';

part 'teacher.g.dart'; // This part file will be generated by json_serializable

/// Class for storing teacher data.
@JsonSerializable()
class Teacher {
  Teacher({
    required this.id,
    required this.fullName,
    required this.shortName,
  });

  factory Teacher.fromJson(Map<String, dynamic> json) =>
      _$TeacherFromJson(json);

  Map<String, dynamic> toJson() => _$TeacherToJson(this);

  @JsonKey(name: 'id')
  final String id;
  @JsonKey(name: 'full_name')
  final String fullName;
  @JsonKey(name: 'short_name')
  final String shortName;
}
