// NureTimetable is an app for viewing schedule for groups or teachers of Kharkiv National University of Radio Electronics.
// Copyright (C) 2023  music-soul1-1

// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.

// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.


import 'package:json_annotation/json_annotation.dart';

part 'theme_colors.g.dart'; // This part file will be generated by json_serializable

/// Class for storing theme colors.
@JsonSerializable()
class ThemeColors {
  ThemeColors({
    required this.lecture,
    required this.practice,
    required this.laboratory,
    required this.consultation,
    required this.exam,
    required this.other,
  });

  factory ThemeColors.fromJson(Map<String, dynamic> json) => _$ThemeColorsFromJson(json);

  Map<String, dynamic> toJson() => _$ThemeColorsToJson(this);

  @JsonKey(name: 'lecture')
  final String lecture;

  @JsonKey(name: 'practice')
  final String practice;

  @JsonKey(name: 'laboratory')
  final String laboratory;

  @JsonKey(name: 'consultation')
  final String consultation;

  @JsonKey(name: 'exam')
  final String exam;

  @JsonKey(name: 'other')
  final String other;
}